### ISSUE TITLE
Support images that are smaller than 512x512px

### ISSUE THREAD

**Issue by mzur** [biigle/maia#28]
The training dataset for Mask R-CNN is composed of 512x512px image crops. Smaller original images are not supported. Maybe change this to use the whole original image if it is smaller than 512x512px? As all training images need to have the same size, pad images with zeros to the largest image (crop) of the dataset (max 512x512).

**Comment by mzur** [comment]
The new pipeline with PyTorch now uses the MMDetection random cropping, which should return smaller images unchanged. I haven't tried, though. Also, novelty detection will be an issue, as it also processes images in 512x512 windows.

**Comment by mzur** [comment]
After the switch to plain PyTorch there was this error:

```

    Traceback (most recent call last):
      File "/var/www/vendor/biigle/maia/src/config/../resources/scripts/object-detection/TrainingRunner.py", line 114, in <module>
        for i, (images, targets) in enumerate(data_loader):
      File "/opt/conda/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 732, in __next__
        data = self._next_data()
               ^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1479, in _next_data
        return self._process_data(data, worker_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1541, in _process_data
        data.reraise()
      File "/opt/conda/lib/python3.11/site-packages/torch/_utils.py", line 769, in reraise
        raise exception
    albumentations.augmentations.crops.transforms.CropSizeError: Caught CropSizeError in DataLoader worker process 1.
    Original Traceback (most recent call last):
      File "/opt/conda/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 349, in _worker_loop
        data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
               ^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
        data = [self.dataset[idx] for idx in possibly_batched_index]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
        data = [self.dataset[idx] for idx in possibly_batched_index]
                ~~~~~~~~~~~~^^^^^
      File "/var/www/vendor/biigle/maia/src/config/../resources/scripts/object-detection/TrainingRunner.py", line 37, in __getitem__
        ret = self.transforms(
              ^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/albumentations/core/composition.py", line 610, in __call__
        data = t(**data)
               ^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/albumentations/core/transforms_interface.py", line 265, in __call__
        params_dependent_on_data = self.get_params_dependent_on_data(params=params, data=kwargs)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/conda/lib/python3.11/site-packages/albumentations/augmentations/crops/transforms.py", line 3565, in get_params_dependent_on_data
        raise CropSizeError(
    albumentations.augmentations.crops.transforms.CropSizeError: Crop size (height, width) exceeds image dimensions (height, width): (1024, 1024) vs (893, 1587)
```
I've changed the issue title. We may need an additional padding step.
